---
- name: Copying files from controller to host
  hosts: planetexpress

  tasks:

          - name: Copy Fry's resume to hosts
            copy:
                    src: ~/ans/files/fryresume.txt  # on the controller
                    #dest: ~/fryresume.txt  #home directory on hosts
                    dest: "/home/{{ ansible_user }}/fryresume.txt"

          - name: Remove the file we just copied over
            file:  
                    path: "/home/{{ ansible_user}}/fryresume.txt"
                    state: absent     
                    
          - name: download a file to my remote servers
            get_url:
                   url: Http://www.clamav.net/downloads/production/clamav-0.99.3.tar.gz
                   dest: ~/clamav-0.99.3.tar.gz         
