---
- name: Intro to looping
  hosts: localhost
  gather_facts: no

  vars:  
        all:

  ethist:
                - eth0
                - eht1
                - eth2
                - eth3
        ethlist2: [eth4, eth5]
  task



